import type { MetadataRoute } from "next";

// Web app manifest — makes Carding installable on desktop and mobile (PWA).
// Next serves this at /manifest.webmanifest and auto-injects <link rel="manifest">.
// Icons live in public/ (generated by scripts/gen-icons.mjs).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Carding — flashcards from anything",
    short_name: "Carding",
    description:
      "Turn documents into high-quality flashcards and study them on a spaced-repetition schedule.",
    id: "/",
    start_url: "/study",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#111111",
    categories: ["education", "productivity"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      { name: "Study due cards", short_name: "Study", url: "/study" },
      { name: "New deck", short_name: "New", url: "/new" },
    ],
  };
}
